[project]
name = "exploring-dask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dask[complete,diagnostics]>=2024.8.2",
    "ipykernel>=6.29.5",
    "numpy>=2.1.1",
]
